## LINUX INTEGRATIONS
general {
    lock_cmd = pidof hyprlock || hyprlock                                     # avoid starting multiple hyprlock instances.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'   # to avoid having to press a key twice to turn on the display.
}

## TURNING MONITORS ON LOW
listener {
    timeout = 360
    on-timeout = brightnessctl -s set 10
    on-resume  = brightnessctl -r
}

## TURNING KEYBOARD LIGHTS OFF
listener {
    timeout = 360
    on-timeout = brightnessctl -sd rgb:kdb_backlight set 0
    on-resume  = brightnessctl -rd rgb:kbd_backlight
}

## LOCK SCREEN
listener {
    timeout = 420
    on-timeout = hyprlock
}

## TURNING SCREEN OFF
listener {
    timeout = 480                                                                                  # 5.5min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                            # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}

## SUSPEND PC
listener {
    timeout = 900                                # 15min
    on-timeout = systemctl suspend                # suspend pc
}
