## LINUX INTEGRATIONS
general {
	hide_cursor = true
	ignore_empty_input = true
	fractional_scaling = 2
	fail_timeout = 10
}

background {
    monitor = DP-1
    path = /home/trfar/Pictures/Wallpapers/Starman.png
    color = rgba(25, 20, 20, 1.0)

    # Optional blur effects
    blur_passes = 2
    blur_size = 7
}

background {
    monitor = DP-2
    path = /home/trfar/Pictures/Wallpapers/Starman-Cropped.png
    color = rgba(25, 20, 20, 1.0)

    # Optional blur effects
    blur_passes = 2
    blur_size = 7
}
