preload = /home/trfar/.config/hypr/Starman.png

wallpaper {
    monitor = DP-1
    path = /home/trfar/Pictures/Wallpapers/Active.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/trfar/Pictures/Wallpapers/Active-Cropped.png
    fit_mode = cover
}

splash = false
