preload = /home/trfar/.config/hypr/Starman.png

wallpaper {
    monitor = DP-1
    path = /home/trfar/.config/hypr/Starman.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/trfar/.config/hypr/Starman-Cropped.png
    fit_mode = cover
}

splash = false
